export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILURE = "ADD_TODO_FAILURE";

export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCESS";
export const DELETE_TODO_FAILURE = "DELETE_TODO_FAILURE";

export const TODO_STATUS_CHANGE_SUCCESS = "TODO_STATUS_CHANGE_SUCCESS";
export const TODO_STATUS_CHANGE_FAILURE = "TODO_STATUS_CHANGE_FAILURE";

export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const FETCH_TODOS_FAILURE = "FETCH_TODOS_FAILURE";

export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_ERROR = "RESET_ERROR";
